prog_lang=('JAVA','C','PYTHON','C++','SQL')
print(type(prog_lang))
print("ACCESSINGLIST ELEMENTS USING+VE INDEXING")
print(prog_lang[0])
print(prog_lang[1])
print(prog_lang[2])
print(prog_lang[3])
print(prog_lang[4])
print("ACCESSINGLIST ELEMENTS USING-VE INDEXING")
print(prog_lang[-5])
print(prog_lang[-4])
print(prog_lang[-3])
print(prog_lang[-2])
print(prog_lang[-1])


