a=int(input("Enter integer value: "))
b=float(input("Enter float value: "))
c=str(input("Enter string: "))
#BEFORE CONVERSION
print(a,b,c)
#AFTER CONVERSION
print("CONVERTING INTEGER")
print(str(a))
print(float(a))
print(complex(a))
print("CONVERTING FLOAT")
print(str(b))
print(int(b))
print(complex(b))
print("CONVERTING STRING")
print(str(c))
print(float(c))
print(list(c))
print(tuple(c))
